Spam Message Detector

In [1]:
#Step 1: import libraries
import pandas as pd
import numpy as np

import re

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [3]:
# STEP 2: CREATE A SMALL BEGINNER DATASET
# ---------------------------------------------------------

# We are creating the dataset manually so it can run directly in Colab
# label = spam or ham
# message = the text message

data = {
    "label": [
        "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam",
        "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam", "ham", "spam"
    ],
    "message": [
        "Hey, are we meeting today?",
        "Congratulations! You won a free iPhone. Click now!",
        "Please send me the notes of today class",
        "Win cash prize now by clicking this link",
        "Can you call me after lunch?",
        "Limited offer! Buy now and get 50 percent discount",
        "I am on the way to college",
        "You have been selected for a free vacation",
        "Let's study together in the evening",
        "Claim your lottery reward today",
        "Can you help me with Python homework?",
        "Urgent! Your account has won a huge reward",
        "Where are you now?",
        "Free entry in contest, click here now",
        "I will reach home by 8 PM",
        "Get a free gift voucher instantly",
        "Did you complete the assignment?",
        "Exclusive deal only for you, act fast",
        "Let's go for tea after class",
        "You are a lucky winner, claim your prize"
    ]
}

# Convert dictionary into DataFrame
df = pd.DataFrame(data)

# Show first 5 rows
print("First 5 rows of dataset:")
display(df.head())

First 5 rows of dataset:


,label,message
0,ham,"Hey, are we meeting today?"
1,spam,Congratulations! You won a free iPhone. Click ...
2,ham,Please send me the notes of today class
3,spam,Win cash prize now by clicking this link
4,ham,Can you call me after lunch?


In [7]:
#step 3:CHECK DATASET INFORMATION
print("\nDataset shape:")
print(df.info)

print("\nColumn names:")
print(df.columns)

print("\nData info:")
print(df.info())

print("\nMissing values:")
print(df.isnull().sum())


Dataset shape:
<bound method DataFrame.info of    label                                            message
0    ham                         Hey, are we meeting today?
1   spam  Congratulations! You won a free iPhone. Click ...
2    ham            Please send me the notes of today class
3   spam           Win cash prize now by clicking this link
4    ham                       Can you call me after lunch?
5   spam  Limited offer! Buy now and get 50 percent disc...
6    ham                         I am on the way to college
7   spam         You have been selected for a free vacation
8    ham                Let's study together in the evening
9   spam                    Claim your lottery reward today
10   ham              Can you help me with Python homework?
11  spam         Urgent! Your account has won a huge reward
12   ham                                 Where are you now?
13  spam              Free entry in contest, click here now
14   ham                          I will reach home 

In [15]:
# STEP 4: TEXT CLEANING FUNCTION
def clean_text(text):
    text = text.lower()
    text = re.sub(r'\d+', '', text)
    text = re.sub(r'[^a-zA-Z\s]', '', text)
    text = re.sub(r'\s+', ' ', text).strip()
    return text

df["clean_message"] = df["message"].apply(clean_text)

print("\nDataset after text cleaning:")
print(df[["message", "clean_message"]].head())


Dataset after text cleaning:
                                             message  \
0                         Hey, are we meeting today?   
1  Congratulations! You won a free iPhone. Click ...   
2            Please send me the notes of today class   
3           Win cash prize now by clicking this link   
4                       Can you call me after lunch?   

                                     clean_message  
0                         hey are we meeting today  
1  congratulations you won a free iphone click now  
2          please send me the notes of today class  
3         win cash prize now by clicking this link  
4                      can you call me after lunch  


In [16]:
# STEP 5: LABEL ENCODING
df["label_encoded"] = LabelEncoder().fit_transform(df["label"])
print("\nOrginal and encoded labels:")
print(df[["label", "label_encoded"]].head())

print("\nLabel mapping:")
for i, class_name in enumerate(LabelEncoder().fit(df["label"]).classes_):
    print(f"{i} = {class_name}")


Orginal and encoded labels:
  label  label_encoded
0   ham              0
1  spam              1
2   ham              0
3  spam              1
4   ham              0

Label mapping:
0 = ham
1 = spam


In [17]:
# STEP 6: SEPARATE FEATURES AND TARGET
X = df["clean_message"]
y = df["label_encoded"]
print("\nFeatures sample:")
print(X.head())
print("\nTarget sampel:")
print(y.head())


Features sample:
0                           hey are we meeting today
1    congratulations you won a free iphone click now
2            please send me the notes of today class
3           win cash prize now by clicking this link
4                        can you call me after lunch
Name: clean_message, dtype: object

Target sampel:
0    0
1    1
2    0
3    1
4    0
Name: label_encoded, dtype: int64


In [19]:
# STEP 7: TRAIN-TEST SPLIT

# We split the data info:
# 80% training data
# 20% testinng data

x_train, x_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print("\nTrain-Test Split Shapes:")
print("X_train:",x_train.shape)
print("X_test:",x_test.shape)
print("y_train:",y_train.shape)
print("y_test:",y_test.shape)


Train-Test Split Shapes:
X_train: (16,)
X_test: (4,)
y_train: (16,)
y_test: (4,)


In [21]:
# STEP 8: CONVERT TEXT INTO NUMBER

vectorizer = CountVectorizer()
x_train_vectorized = vectorizer.fit_transform(x_train)
x_test_vectorized = vectorizer.transform(x_test)

print("\nShape after vectorization:")
print("x_train_vectorized:", x_train_vectorized.shape)
print("x_test_vectorized:",x_test_vectorized.shape)

print("\nSample of vectorized words:")
print(list(vectorizer.vocabulary_.keys())[:10])


Shape after vectorization:
x_train_vectorized: (16, 74)
x_test_vectorized: (4, 74)

Sample of vectorized words:
['lets', 'study', 'together', 'in', 'the', 'evening', 'limited', 'offer', 'buy', 'now']


In [22]:
# STEP 9: TRAIN THE MODEL
model = MultinomialNB()
model.fit(x_train_vectorized, y_train)
print("\nModel trained successfully!")



Model trained successfully!


In [23]:
# STEP 10: MAKE PREDICTIONS
y_pred = model.predict(x_test_vectorized)
print("\nPredictions values:")
print(y_pred)
print("\nActual values:")
print(y_test.values)


Predictions values:
[0 0 1 1]

Actual values:
[0 1 1 1]


In [24]:
# STEP 11: EVALUATE THE MODEL

accuracy = accuracy_score(y_test, y_pred)
print("\nAccuracy of model:")
print(accuracy)
print("\nClassification Report:")
print(classification_report(y_test, y_pred))
print("\nConfusion Matrix:")
print(confusion_matrix(y_test, y_pred))


Accuracy of model:
0.75

Classification Report:
              precision    recall  f1-score   support

           0       0.50      1.00      0.67         1
           1       1.00      0.67      0.80         3

    accuracy                           0.75         4
   macro avg       0.75      0.83      0.73         4
weighted avg       0.88      0.75      0.77         4


Confusion Matrix:
[[1 0]
 [1 2]]


In [26]:
# STEP 12: TEST WITH NEW CUSTOM MESSAGE
new_messages =[
    "Congratulations! You have won a free gift",
    "Can you send me the class link?",
    "Claim your case prize now",
    "I am coming in 10 munites",
    "Exclusive offer only today buy now"
]
cleaned_new_message = [clean_text(msg) for msg in new_messages]
new_message_vectorized = vectorizer.transform(cleaned_new_message)
new_predictions = model.predict(new_message_vectorized)
print("\nPredictions for new messages:")

# Re-instantiate and fit LabelEncoder for inverse_transform as it wasn't saved previously
le = LabelEncoder()
le.fit(df["label"]) # Fit the encoder with the original labels

for msg, prediction in zip(new_messages, new_predictions):
  label_name = le.inverse_transform([prediction])[0]
  print(f"Message: {msg}\nPredicted Label: {label_name}\n")
  print("-" * 50)


Predictions for new messages:
Message: Congratulations! You have won a free gift
Predicted Label: spam

--------------------------------------------------
Message: Can you send me the class link?
Predicted Label: ham

--------------------------------------------------
Message: Claim your case prize now
Predicted Label: spam

--------------------------------------------------
Message: I am coming in 10 munites
Predicted Label: ham

--------------------------------------------------
Message: Exclusive offer only today buy now
Predicted Label: spam

--------------------------------------------------
